# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ printf "%s-pool" .Values.environment }}
      tolerations:
        - key: "env"
          operator: "Equal"
          value: {{ .Values.environment }}
          effect: "NoSchedule"
      dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
        - name: {{ include "app.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}