# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: crypto-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: crypto-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080